### ISSUE TITLE
(BUG) HTML crash

### ISSUE THREAD

**Issue by Martinator9001** [Project-Sloth/ps-brand#3]
Getting "Uncaught SyntaxError: 40 (https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js:1)" in client and the menu doesn't open, only mouse appears.
![image](https://github.com/Project-Sloth/ps-brand/assets/90502234/97fd891b-3f5c-4e52-b52e-2267c30e880a)

**Comment by Martinator9001** [comment]
The logo appears though.

**Comment by xFutte** [comment]
How do you expect this to be fixed if nobody knows how you encountered the issue?

**Comment by MonkeyWhisper** [comment]
User error

**Comment by Martinator9001** [comment]
Every time I open the checklist using /checklist it happens
